return {
    {
        "nvim-treesitter/nvim-treesitter",
        branch = "main",
        lazy = false,
        build = ":TSUpdate",
        config = function()
            require("nvim-treesitter").install({
                "bash",
                "c",
                "cmake",
                "cpp",
                "css",
                "gitignore",
                "diff",
                "go",
                "graphql",
                "html",
                "http",
                "java",
                "javascript",
                "jsdoc",
                "jsonc",
                "kotlin",
                "latex",
                "lua",
                "markdown",
                "markdown_inline",
                "php",
                "python",
                "query",
                "regex",
                "rust",
                "scss",
                "sql",
                "svelte",
                "toml",
                "tsx",
                "typescript",
                "vim",
                "vue",
                "wgsl",
                "yaml",
                "wgsl",
                "json",
                "markdown",
                "terraform",
            })

            vim.api.nvim_create_autocmd('FileType', {
                pattern = {
                    "bash",
                    "c",
                    "cmake",
                    "cpp",
                    "css",
                    "gitignore",
                    "diff",
                    "go",
                    "graphql",
                    "html",
                    "http",
                    "java",
                    "javascript",
                    "jsdoc",
                    "jsonc",
                    "kotlin",
                    "latex",
                    "lua",
                    "markdown",
                    "markdown_inline",
                    "php",
                    "python",
                    "query",
                    "regex",
                    "rust",
                    "scss",
                    "sql",
                    "svelte",
                    "toml",
                    "tsx",
                    "typescript",
                    "typescriptreact",
                    "vim",
                    "vue",
                    "wgsl",
                    "yaml",
                    "wgsl",
                    "json",
                    "markdown",
                    "terraform",
                },
                callback = function() vim.treesitter.start() end,
            })

            vim.wo.foldmethod = 'expr'
            vim.wo.foldexpr = 'v:lua.vim.treesitter.foldexpr()'
            vim.wo.foldlevel = 99
        end
    },
}
